- name: Deploy Contínuo da Aplicação
  hosts: servidor
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
    aws_region: us-east-1

  tasks:
    - name: Copiar Docker Compose atualizado
      copy:
        src: ../docker/docker-compose.yml
        dest: /home/ubuntu/docker-compose.yml
        owner: ubuntu
        group: ubuntu
        mode: '0644'

    - name: Criar arquivo .env para o Compose
      copy:
        dest: /home/ubuntu/.env
        content: |
          AWS_ACCOUNT_ID={{ lookup('env', 'AWS_ACCOUNT_ID') }}
        owner: ubuntu
        group: ubuntu
        mode: '0600'

    - name: Login no AWS ECR no servidor
      shell: "aws ecr get-login-password --region {{ aws_region }} | docker login --username AWS --password-stdin {{ lookup('env', 'AWS_ACCOUNT_ID') }}.dkr.ecr.{{ aws_region }}.amazonaws.com"
      changed_when: false

    - name: Pull das imagens e Up dos containers
      community.docker.docker_compose_v2:
        project_src: /home/ubuntu
        state: present
        pull: always  