#instalar dependências necessárias para rodar o app no servidor

- name: Provisionamento de Infraestrutura (Base)
  hosts: all                
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Atualizar apt
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Instalar dependências base (sem awscli)
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - gnupg
          - unzip
          - lsb-release
        state: present

    - name: Baixar instalador do AWS CLI v2
      get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip

    - name: Descompactar instalador
      unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes

    - name: Instalar AWS CLI v2
      shell: /tmp/aws/install
      args:
        creates: /usr/local/bin/aws

    - name: Configurar Repositório e Chave GPG do Docker
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg --yes
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" > /etc/apt/sources.list.d/docker.list
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Instalar Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        update_cache: yes
        state: present

    - name: Garantir que o Docker está rodando
      service:
        name: docker
        state: started
        enabled: yes